name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pygame
          python -m pip install numpy
      - name: Check NumPy installation
        run: |
          if pip list | grep -q "numpy"; then
            echo "NumPy is installed"
          else
            echo "NumPy is not installed"
          fi
      - name: Check Pygame installation
        run: |
          if pip list | grep -q "pygame"; then
            echo "Pygame is installed"
          else
            echo "Pygame is not installed"
          fi

